language: python
python:
  - "3.4"

# command to install dependencies
install:
  - pip install flake8

# command to run tests
before_script:
  - flake8 simpleyapsy
script: 
  - coverage run -m unittest discover

after_success:
  - coverage report
  - coveralls
