language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

matrix:
  include:
    - os: linux
      python: 3.5
      env: TEST_MODE='doctest'

  allow_failures:
    - env: TEST_MODE='doctest'

# command to install dependencies
install:
  - pip install flake8
  - if [[ $TEST_MODE == 'doctest' ]]; then pip install sphinx; fi
  - pip install coverage
  - pip install python-coveralls

# command to run tests
script: 
  - coverage run -m unittest discover
  - flake8 pluginmanager
  - flake8 tests
  - if [[ $TEST_MODE == 'doctest' ]]; then make -C docs doctest; fi
  
after_success:
  - coverage report
  - coveralls
